version: '3'
services:
  api:
    build: ..
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - prisma
      - postgres
    command: yarn test

  prisma:
    image: prismagraphql/prisma:1.8
    restart: always
    ports:
    - ${PRISMA_PORT}:${PRISMA_PORT}
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: postgres
            port: ${PSQL_PORT}
            user: ${PSQL_USER}
            password: ${PSQL_PASSWORD}
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
